// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module xilly_decprint (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        val_r,
        debug_ready,
        debug_out,
        debug_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] val_r;
input  [7:0] debug_ready;
output  [7:0] debug_out;
output   debug_out_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg debug_out_ap_vld;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] powers10_address0;
reg    powers10_ce0;
wire   [27:0] powers10_q0;
wire   [31:0] zext_ln37_fu_139_p1;
reg   [31:0] zext_ln37_reg_273;
wire    ap_CS_fsm_state2;
wire   [3:0] i_fu_149_p2;
reg   [3:0] i_reg_282;
wire   [63:0] zext_ln39_fu_155_p1;
reg   [63:0] zext_ln39_reg_287;
wire   [0:0] icmp_ln37_fu_143_p2;
wire   [4:0] trunc_ln6_fu_160_p1;
reg   [4:0] trunc_ln6_reg_297;
wire   [31:0] zext_ln39_1_fu_168_p1;
reg   [31:0] zext_ln39_1_reg_302;
wire    ap_CS_fsm_state3;
wire   [7:0] x_fu_180_p2;
wire    ap_CS_fsm_state4;
wire   [31:0] first_1_fu_220_p3;
wire   [0:0] icmp_ln39_fu_175_p2;
wire    ap_CS_fsm_state5;
wire   [63:0] add_ln9_fu_241_p2;
reg   [63:0] add_ln9_reg_326;
wire   [7:0] out_q0;
reg   [7:0] out_load_reg_331;
wire    ap_CS_fsm_state6;
reg   [3:0] out_address0;
reg    out_ce0;
reg    out_we0;
reg   [7:0] out_d0;
reg   [31:0] first_0_reg_89;
reg   [3:0] first_reg_101;
reg   [7:0] x_0_reg_112;
reg   [63:0] p_0_rec_i_reg_123;
wire    ap_CS_fsm_state7;
wire   [0:0] trunc_ln8_fu_257_p1;
wire   [63:0] sum_i_cast_fu_236_p1;
reg   [31:0] v_0_fu_34;
wire   [31:0] v_fu_186_p2;
wire   [7:0] or_ln44_fu_196_p2;
wire  signed [29:0] sext_ln39_fu_164_p1;
wire   [0:0] icmp_ln46_fu_203_p2;
wire   [0:0] icmp_ln46_1_fu_209_p2;
wire   [0:0] and_ln46_fu_214_p2;
wire   [4:0] empty_29_fu_227_p1;
wire   [4:0] sum_i_fu_231_p2;
wire   [0:0] icmp_ln7_fu_247_p2;
reg   [6:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
end

xilly_decprint_pobkb #(
    .DataWidth( 28 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
powers10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(powers10_address0),
    .ce0(powers10_ce0),
    .q0(powers10_q0)
);

xilly_decprint_out #(
    .DataWidth( 8 ),
    .AddressRange( 11 ),
    .AddressWidth( 4 ))
out_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(out_address0),
    .ce0(out_ce0),
    .we0(out_we0),
    .d0(out_d0),
    .q0(out_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_fu_175_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        first_0_reg_89 <= first_1_fu_220_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        first_0_reg_89 <= 32'd9;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_fu_175_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        first_reg_101 <= i_reg_282;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        first_reg_101 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln8_fu_257_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        p_0_rec_i_reg_123 <= add_ln9_reg_326;
    end else if (((icmp_ln37_fu_143_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        p_0_rec_i_reg_123 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_fu_175_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        v_0_fu_34 <= v_fu_186_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        v_0_fu_34 <= val_r;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        x_0_reg_112 <= 8'd0;
    end else if (((icmp_ln39_fu_175_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        x_0_reg_112 <= x_fu_180_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln9_reg_326 <= add_ln9_fu_241_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_282 <= i_fu_149_p2;
        zext_ln37_reg_273[3 : 0] <= zext_ln37_fu_139_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        out_load_reg_331 <= out_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_fu_143_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        trunc_ln6_reg_297 <= trunc_ln6_fu_160_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        zext_ln39_1_reg_302[29 : 0] <= zext_ln39_1_fu_168_p1[29 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_fu_143_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        zext_ln39_reg_287[3 : 0] <= zext_ln39_fu_155_p1[3 : 0];
    end
end

always @ (*) begin
    if ((((icmp_ln7_fu_247_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln7_fu_247_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln8_fu_257_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        debug_out_ap_vld = 1'b1;
    end else begin
        debug_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_address0 = sum_i_cast_fu_236_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_address0 = zext_ln39_reg_287;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_address0 = 64'd10;
    end else begin
        out_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2))) begin
        out_ce0 = 1'b1;
    end else begin
        out_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out_d0 = or_ln44_fu_196_p2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_d0 = 8'd0;
    end else begin
        out_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln39_fu_175_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((icmp_ln37_fu_143_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        out_we0 = 1'b1;
    end else begin
        out_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        powers10_ce0 = 1'b1;
    end else begin
        powers10_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln37_fu_143_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln39_fu_175_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((icmp_ln7_fu_247_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((trunc_ln8_fu_257_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln9_fu_241_p2 = (64'd1 + p_0_rec_i_reg_123);

assign and_ln46_fu_214_p2 = (icmp_ln46_fu_203_p2 & icmp_ln46_1_fu_209_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign debug_out = out_load_reg_331;

assign empty_29_fu_227_p1 = p_0_rec_i_reg_123[4:0];

assign first_1_fu_220_p3 = ((and_ln46_fu_214_p2[0:0] === 1'b1) ? zext_ln37_reg_273 : first_0_reg_89);

assign i_fu_149_p2 = (first_reg_101 + 4'd1);

assign icmp_ln37_fu_143_p2 = ((first_reg_101 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_175_p2 = ((v_0_fu_34 < zext_ln39_1_reg_302) ? 1'b1 : 1'b0);

assign icmp_ln46_1_fu_209_p2 = (($signed(first_0_reg_89) > $signed(zext_ln37_reg_273)) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_203_p2 = ((x_0_reg_112 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln7_fu_247_p2 = ((out_q0 == 8'd0) ? 1'b1 : 1'b0);

assign or_ln44_fu_196_p2 = (x_0_reg_112 | 8'd48);

assign powers10_address0 = zext_ln39_fu_155_p1;

assign sext_ln39_fu_164_p1 = $signed(powers10_q0);

assign sum_i_cast_fu_236_p1 = sum_i_fu_231_p2;

assign sum_i_fu_231_p2 = (empty_29_fu_227_p1 + trunc_ln6_reg_297);

assign trunc_ln6_fu_160_p1 = first_0_reg_89[4:0];

assign trunc_ln8_fu_257_p1 = debug_ready[0:0];

assign v_fu_186_p2 = (v_0_fu_34 - zext_ln39_1_reg_302);

assign x_fu_180_p2 = (x_0_reg_112 + 8'd1);

assign zext_ln37_fu_139_p1 = first_reg_101;

assign zext_ln39_1_fu_168_p1 = $unsigned(sext_ln39_fu_164_p1);

assign zext_ln39_fu_155_p1 = first_reg_101;

always @ (posedge ap_clk) begin
    zext_ln37_reg_273[31:4] <= 28'b0000000000000000000000000000;
    zext_ln39_reg_287[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln39_1_reg_302[31:30] <= 2'b00;
end

endmodule //xilly_decprint
