// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="xillybus_wrapper,hls_ip_2019_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.665000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=13,HLS_SYN_FF=2077,HLS_SYN_LUT=3442,HLS_VERSION=2019_1}" *)

module xillybus_wrapper (
        ap_clk,
        ap_rst,
        in_r_dout,
        in_r_empty_n,
        in_r_read,
        out_r_din,
        out_r_full_n,
        out_r_write,
        debug_ready,
        debug_out,
        debug_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 27'd1;
parameter    ap_ST_fsm_state2 = 27'd2;
parameter    ap_ST_fsm_state3 = 27'd4;
parameter    ap_ST_fsm_state4 = 27'd8;
parameter    ap_ST_fsm_state5 = 27'd16;
parameter    ap_ST_fsm_state6 = 27'd32;
parameter    ap_ST_fsm_state7 = 27'd64;
parameter    ap_ST_fsm_state8 = 27'd128;
parameter    ap_ST_fsm_state9 = 27'd256;
parameter    ap_ST_fsm_state10 = 27'd512;
parameter    ap_ST_fsm_state11 = 27'd1024;
parameter    ap_ST_fsm_state12 = 27'd2048;
parameter    ap_ST_fsm_state13 = 27'd4096;
parameter    ap_ST_fsm_state14 = 27'd8192;
parameter    ap_ST_fsm_state15 = 27'd16384;
parameter    ap_ST_fsm_state16 = 27'd32768;
parameter    ap_ST_fsm_state17 = 27'd65536;
parameter    ap_ST_fsm_state18 = 27'd131072;
parameter    ap_ST_fsm_state19 = 27'd262144;
parameter    ap_ST_fsm_state20 = 27'd524288;
parameter    ap_ST_fsm_state21 = 27'd1048576;
parameter    ap_ST_fsm_state22 = 27'd2097152;
parameter    ap_ST_fsm_state23 = 27'd4194304;
parameter    ap_ST_fsm_state24 = 27'd8388608;
parameter    ap_ST_fsm_state25 = 27'd16777216;
parameter    ap_ST_fsm_state26 = 27'd33554432;
parameter    ap_ST_fsm_state27 = 27'd67108864;

input   ap_clk;
input   ap_rst;
input  [31:0] in_r_dout;
input   in_r_empty_n;
output   in_r_read;
output  [31:0] out_r_din;
input   out_r_full_n;
output   out_r_write;
input  [7:0] debug_ready;
output  [7:0] debug_out;
output   debug_out_ap_vld;

reg in_r_read;
reg[31:0] out_r_din;
reg out_r_write;
reg[7:0] debug_out;
reg debug_out_ap_vld;

wire   [3:0] p_str3_address0;
reg    p_str3_ce0;
wire   [6:0] p_str3_q0;
wire   [1:0] p_str4_address0;
reg    p_str4_ce0;
wire   [6:0] p_str4_q0;
wire   [0:0] p_str5_address0;
reg    p_str5_ce0;
wire   [3:0] p_str5_q0;
wire   [3:0] ref_4oPi_table_100_V_address0;
reg    ref_4oPi_table_100_V_ce0;
wire   [99:0] ref_4oPi_table_100_V_q0;
wire   [7:0] second_order_float_2_address0;
reg    second_order_float_2_ce0;
wire   [29:0] second_order_float_2_q0;
wire   [7:0] second_order_float_3_address0;
reg    second_order_float_3_ce0;
wire   [22:0] second_order_float_3_q0;
wire   [7:0] second_order_float_s_address0;
reg    second_order_float_s_ce0;
wire   [14:0] second_order_float_s_q0;
reg    in_r_blk_n;
(* fsm_encoding = "none" *) reg   [26:0] ap_CS_fsm;
wire    ap_CS_fsm_state3;
reg   [0:0] icmp_ln7_reg_1153;
wire    ap_CS_fsm_state5;
reg    out_r_blk_n;
wire    ap_CS_fsm_state11;
reg   [0:0] phi_ln7_2_reg_327;
wire    ap_CS_fsm_state27;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln7_fu_367_p2;
wire   [3:0] add_ln9_fu_373_p2;
reg   [3:0] add_ln9_reg_1157;
wire   [7:0] zext_ln7_fu_379_p1;
reg   [7:0] zext_ln7_reg_1162;
reg    ap_block_state3;
reg   [31:0] x1_reg_1167;
reg   [31:0] tmp_8_reg_1176;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln7_1_fu_397_p2;
reg   [0:0] icmp_ln7_1_reg_1188;
wire   [1:0] add_ln9_1_fu_403_p2;
reg   [1:0] add_ln9_1_reg_1192;
wire   [7:0] zext_ln7_1_fu_409_p1;
reg   [7:0] zext_ln7_1_reg_1197;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state10;
wire   [7:0] zext_ln7_2_fu_427_p1;
reg   [7:0] zext_ln7_2_reg_1210;
reg    ap_block_state11;
reg   [0:0] results_sign_V_1_reg_1215;
wire   [7:0] tmp_V_fu_438_p4;
reg   [7:0] tmp_V_reg_1221;
wire   [22:0] tmp_V_1_fu_447_p1;
reg   [22:0] tmp_V_1_reg_1228;
wire   [0:0] closepath_fu_450_p2;
reg   [0:0] closepath_reg_1234;
wire   [3:0] trunc_ln601_fu_485_p1;
reg   [3:0] trunc_ln601_reg_1245;
reg   [79:0] Med_V_reg_1253;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire   [0:0] icmp_ln833_1_fu_543_p2;
reg   [0:0] icmp_ln833_1_reg_1268;
reg   [57:0] p_Val2_s_reg_1274;
wire    ap_CS_fsm_state18;
reg   [2:0] trunc_ln_i_i_reg_1280;
wire   [2:0] p_Val2_24_fu_568_p3;
reg   [2:0] p_Val2_24_reg_1285;
wire    ap_CS_fsm_state19;
wire   [57:0] p_Val2_7_fu_583_p3;
reg   [57:0] p_Val2_7_reg_1291;
wire   [4:0] Mx_zeros_V_fu_634_p1;
reg   [4:0] Mx_zeros_V_reg_1296;
reg   [28:0] Mx_V_reg_1302;
wire    ap_CS_fsm_state20;
wire  signed [7:0] Ex_V_fu_671_p2;
reg  signed [7:0] Ex_V_reg_1309;
wire   [0:0] isNeg_fu_681_p3;
reg   [0:0] isNeg_reg_1314;
wire  signed [8:0] ush_fu_695_p3;
reg  signed [8:0] ush_reg_1319;
wire   [0:0] icmp_ln833_fu_703_p2;
reg   [0:0] icmp_ln833_reg_1325;
wire   [0:0] icmp_ln833_2_fu_708_p2;
reg   [0:0] icmp_ln833_2_reg_1331;
wire   [0:0] cos_basis_fu_744_p10;
reg   [0:0] cos_basis_reg_1338;
wire    ap_CS_fsm_state21;
wire   [21:0] B_V_fu_775_p1;
reg   [21:0] B_V_reg_1345;
reg   [14:0] B_trunc_V_reg_1350;
reg   [14:0] B_squared_V_reg_1370;
wire    ap_CS_fsm_state22;
reg   [28:0] t1_V_reg_1375;
reg   [22:0] second_order_float_6_reg_1380;
reg  signed [14:0] second_order_float_8_reg_1385;
reg   [21:0] trunc_ln1_reg_1390;
wire    ap_CS_fsm_state23;
reg   [13:0] trunc_ln662_1_reg_1395;
wire   [28:0] select_ln272_1_fu_869_p3;
reg   [28:0] select_ln272_1_reg_1400;
wire    ap_CS_fsm_state24;
wire   [29:0] ret_V_fu_890_p2;
reg   [29:0] ret_V_reg_1405;
reg   [28:0] result_V_reg_1410;
wire    ap_CS_fsm_state25;
wire   [8:0] ret_V_9_fu_929_p2;
reg   [8:0] ret_V_9_reg_1415;
wire   [0:0] and_ln300_fu_1051_p2;
reg   [0:0] and_ln300_reg_1420;
wire    ap_CS_fsm_state26;
wire    grp_scaled_fixed2ieee_fu_341_ap_ready;
wire    grp_scaled_fixed2ieee_fu_341_ap_done;
wire   [0:0] select_ln311_fu_1065_p3;
reg   [0:0] select_ln311_reg_1425;
wire   [7:0] ret_V_10_fu_1096_p3;
reg   [7:0] ret_V_10_reg_1430;
wire   [22:0] ret_V_11_fu_1112_p3;
reg   [22:0] ret_V_11_reg_1435;
wire    grp_scaled_fixed2ieee_fu_341_ap_start;
wire    grp_scaled_fixed2ieee_fu_341_ap_idle;
wire   [31:0] grp_scaled_fixed2ieee_fu_341_ap_return;
wire    grp_xilly_decprint_fu_347_ap_start;
wire    grp_xilly_decprint_fu_347_ap_done;
wire    grp_xilly_decprint_fu_347_ap_idle;
wire    grp_xilly_decprint_fu_347_ap_ready;
wire   [7:0] grp_xilly_decprint_fu_347_debug_out;
wire    grp_xilly_decprint_fu_347_debug_out_ap_vld;
reg   [3:0] phi_ln7_reg_305;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state4;
wire   [0:0] trunc_ln8_fu_383_p1;
reg   [1:0] phi_ln7_1_reg_316;
wire    ap_CS_fsm_state8;
wire   [0:0] trunc_ln8_1_fu_413_p1;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state12;
wire   [0:0] trunc_ln8_2_fu_495_p1;
reg    grp_scaled_fixed2ieee_fu_341_ap_start_reg;
reg    grp_xilly_decprint_fu_347_ap_start_reg;
wire   [63:0] phi_ln7_cast_fu_362_p1;
wire   [63:0] phi_ln7_1_cast_fu_392_p1;
wire   [63:0] phi_ln7_2_cast_fu_422_p1;
wire   [63:0] zext_ln498_fu_480_p1;
wire   [63:0] zext_ln498_1_fu_803_p1;
wire   [31:0] y1_fu_489_p2;
wire   [31:0] p_Result_21_fu_1125_p4;
wire   [7:0] add_ln114_1_fu_456_p2;
wire   [7:0] addr_V_fu_462_p3;
wire   [3:0] tmp_3_fu_470_p4;
wire   [99:0] zext_ln744_fu_504_p1;
wire   [99:0] r_V_9_fu_507_p2;
wire   [23:0] p_Result_15_fu_523_p3;
wire   [79:0] grp_fu_537_p0;
wire   [23:0] grp_fu_537_p1;
wire   [103:0] grp_fu_537_p2;
wire   [0:0] trunc_ln745_fu_574_p1;
wire   [57:0] Mx_bits_V_1_fu_578_p2;
wire   [28:0] p_Result_i_i_i_fu_590_p4;
wire   [29:0] p_Result_16_fu_600_p3;
reg   [29:0] p_Result_s_fu_608_p4;
wire   [31:0] p_Result_17_fu_618_p3;
reg   [31:0] val_assign_fu_626_p3;
wire   [7:0] add_ln114_fu_638_p2;
wire   [57:0] zext_ln1253_fu_650_p1;
wire   [57:0] r_V_10_fu_653_p2;
wire   [7:0] select_ln482_fu_643_p3;
wire   [7:0] zext_ln655_fu_668_p1;
wire  signed [8:0] sext_ln1334_fu_677_p1;
wire   [8:0] sub_ln1311_fu_689_p2;
wire  signed [28:0] sext_ln1311_1_fu_716_p1;
wire   [28:0] lshr_ln1287_fu_722_p2;
wire   [31:0] zext_ln1287_fu_719_p1;
wire  signed [31:0] sext_ln1311_fu_713_p1;
wire   [31:0] zext_ln1287_1_fu_727_p1;
wire   [31:0] shl_ln1253_fu_731_p2;
wire   [31:0] select_ln1310_fu_737_p3;
wire   [0:0] sin_basis_fu_789_p2;
wire   [6:0] p_Result_i_i_fu_765_p4;
wire   [7:0] p_Result_18_fu_795_p3;
wire   [29:0] r_V_11_fu_1134_p2;
wire  signed [22:0] r_V_12_fu_838_p0;
wire   [21:0] r_V_12_fu_838_p1;
wire   [44:0] r_V_12_fu_838_p2;
wire  signed [29:0] r_V_13_fu_1141_p2;
wire  signed [29:0] lhs_V_1_fu_875_p1;
wire  signed [29:0] rhs_V_1_fu_878_p1;
wire   [29:0] ret_V_13_fu_881_p2;
wire  signed [29:0] sext_ln657_fu_887_p1;
wire  signed [29:0] r_V_14_fu_908_p0;
wire   [28:0] r_V_14_fu_908_p1;
wire   [57:0] r_V_14_fu_908_p2;
wire   [7:0] select_ln272_fu_896_p3;
wire  signed [8:0] rhs_V_2_fu_925_p1;
wire   [31:0] p_Val2_20_fu_936_p1;
wire   [3:0] p_Result_20_fu_962_p3;
wire   [0:0] tmp_fu_968_p18;
wire   [0:0] tmp_1_fu_1006_p18;
wire   [0:0] select_ln271_fu_1044_p3;
wire   [0:0] or_ln311_fu_1060_p2;
wire   [0:0] xor_ln311_fu_1055_p2;
wire   [0:0] p_Result_19_fu_940_p3;
wire   [0:0] and_ln300_1_fu_1073_p2;
wire   [0:0] xor_ln300_fu_1077_p2;
wire   [0:0] or_ln300_fu_1091_p2;
wire   [7:0] select_ln300_1_fu_1083_p3;
wire   [7:0] tmp_V_2_fu_948_p4;
wire   [22:0] select_ln300_3_fu_1104_p3;
wire   [22:0] tmp_V_3_fu_958_p1;
wire   [0:0] p_Repl2_3_fu_1120_p3;
wire   [14:0] r_V_11_fu_1134_p0;
wire   [29:0] r_V_fu_810_p1;
wire   [14:0] r_V_11_fu_1134_p1;
wire   [14:0] r_V_13_fu_1141_p0;
reg   [26:0] ap_NS_fsm;
wire   [103:0] grp_fu_537_p00;
wire   [103:0] grp_fu_537_p10;
wire   [44:0] r_V_12_fu_838_p10;
wire   [29:0] r_V_13_fu_1141_p00;
wire   [57:0] r_V_14_fu_908_p10;

// power-on initialization
initial begin
#0 ap_CS_fsm = 27'd1;
#0 grp_scaled_fixed2ieee_fu_341_ap_start_reg = 1'b0;
#0 grp_xilly_decprint_fu_347_ap_start_reg = 1'b0;
end

xillybus_wrapper_cud #(
    .DataWidth( 7 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
p_str3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_str3_address0),
    .ce0(p_str3_ce0),
    .q0(p_str3_q0)
);

xillybus_wrapper_dEe #(
    .DataWidth( 7 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
p_str4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_str4_address0),
    .ce0(p_str4_ce0),
    .q0(p_str4_q0)
);

xillybus_wrapper_eOg #(
    .DataWidth( 4 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
p_str5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_str5_address0),
    .ce0(p_str5_ce0),
    .q0(p_str5_q0)
);

xillybus_wrapper_fYi #(
    .DataWidth( 100 ),
    .AddressRange( 13 ),
    .AddressWidth( 4 ))
ref_4oPi_table_100_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ref_4oPi_table_100_V_address0),
    .ce0(ref_4oPi_table_100_V_ce0),
    .q0(ref_4oPi_table_100_V_q0)
);

xillybus_wrapper_g8j #(
    .DataWidth( 30 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
second_order_float_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(second_order_float_2_address0),
    .ce0(second_order_float_2_ce0),
    .q0(second_order_float_2_q0)
);

xillybus_wrapper_hbi #(
    .DataWidth( 23 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
second_order_float_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(second_order_float_3_address0),
    .ce0(second_order_float_3_ce0),
    .q0(second_order_float_3_q0)
);

xillybus_wrapper_ibs #(
    .DataWidth( 15 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
second_order_float_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(second_order_float_s_address0),
    .ce0(second_order_float_s_ce0),
    .q0(second_order_float_s_q0)
);

scaled_fixed2ieee grp_scaled_fixed2ieee_fu_341(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_scaled_fixed2ieee_fu_341_ap_start),
    .ap_done(grp_scaled_fixed2ieee_fu_341_ap_done),
    .ap_idle(grp_scaled_fixed2ieee_fu_341_ap_idle),
    .ap_ready(grp_scaled_fixed2ieee_fu_341_ap_ready),
    .in_V(result_V_reg_1410),
    .prescale(ret_V_9_reg_1415),
    .ap_return(grp_scaled_fixed2ieee_fu_341_ap_return)
);

xilly_decprint grp_xilly_decprint_fu_347(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xilly_decprint_fu_347_ap_start),
    .ap_done(grp_xilly_decprint_fu_347_ap_done),
    .ap_idle(grp_xilly_decprint_fu_347_ap_idle),
    .ap_ready(grp_xilly_decprint_fu_347_ap_ready),
    .val_r(x1_reg_1167),
    .debug_ready(debug_ready),
    .debug_out(grp_xilly_decprint_fu_347_debug_out),
    .debug_out_ap_vld(grp_xilly_decprint_fu_347_debug_out_ap_vld)
);

xillybus_wrapper_jbC #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 80 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 104 ))
xillybus_wrapper_jbC_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_537_p0),
    .din1(grp_fu_537_p1),
    .ce(1'b1),
    .dout(grp_fu_537_p2)
);

xillybus_wrapper_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
xillybus_wrapper_kbM_U9(
    .din0(1'd0),
    .din1(1'd1),
    .din2(1'd1),
    .din3(1'd0),
    .din4(1'd0),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .din8(p_Val2_24_reg_1285),
    .dout(cos_basis_fu_744_p10)
);

xillybus_wrapper_lbW #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
xillybus_wrapper_lbW_U10(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd0),
    .din3(1'd1),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .din8(1'd0),
    .din9(1'd1),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd1),
    .din13(1'd0),
    .din14(1'd0),
    .din15(1'd0),
    .din16(p_Result_20_fu_962_p3),
    .dout(tmp_fu_968_p18)
);

xillybus_wrapper_lbW #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
xillybus_wrapper_lbW_U11(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd1),
    .din3(1'd0),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd0),
    .din7(1'd1),
    .din8(1'd1),
    .din9(1'd0),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd0),
    .din13(1'd1),
    .din14(1'd0),
    .din15(1'd0),
    .din16(p_Result_20_fu_962_p3),
    .dout(tmp_1_fu_1006_p18)
);

xillybus_wrapper_mb6 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
xillybus_wrapper_mb6_U12(
    .din0(r_V_11_fu_1134_p0),
    .din1(r_V_11_fu_1134_p1),
    .dout(r_V_11_fu_1134_p2)
);

xillybus_wrapper_ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
xillybus_wrapper_ncg_U13(
    .din0(r_V_13_fu_1141_p0),
    .din1(second_order_float_8_reg_1385),
    .dout(r_V_13_fu_1141_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_scaled_fixed2ieee_fu_341_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state25)) begin
            grp_scaled_fixed2ieee_fu_341_ap_start_reg <= 1'b1;
        end else if ((grp_scaled_fixed2ieee_fu_341_ap_ready == 1'b1)) begin
            grp_scaled_fixed2ieee_fu_341_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xilly_decprint_fu_347_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln7_1_reg_1188 == 1'd1))) begin
            grp_xilly_decprint_fu_347_ap_start_reg <= 1'b1;
        end else if ((grp_xilly_decprint_fu_347_ap_ready == 1'b1)) begin
            grp_xilly_decprint_fu_347_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (trunc_ln8_1_fu_413_p1 == 1'd1))) begin
        phi_ln7_1_reg_316 <= add_ln9_1_reg_1192;
    end else if (((in_r_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        phi_ln7_1_reg_316 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (trunc_ln8_2_fu_495_p1 == 1'd1))) begin
        phi_ln7_2_reg_327 <= 1'd1;
    end else if (((grp_xilly_decprint_fu_347_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        phi_ln7_2_reg_327 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln8_fu_383_p1 == 1'd1))) begin
        phi_ln7_reg_305 <= add_ln9_reg_1157;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        phi_ln7_reg_305 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        B_V_reg_1345 <= B_V_fu_775_p1;
        B_trunc_V_reg_1350 <= {{select_ln1310_fu_737_p3[21:7]}};
        cos_basis_reg_1338 <= cos_basis_fu_744_p10;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        B_squared_V_reg_1370 <= {{r_V_11_fu_1134_p2[29:15]}};
        second_order_float_6_reg_1380 <= second_order_float_3_q0;
        second_order_float_8_reg_1385 <= second_order_float_s_q0;
        t1_V_reg_1375 <= {{second_order_float_2_q0[29:1]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        Ex_V_reg_1309 <= Ex_V_fu_671_p2;
        Mx_V_reg_1302 <= {{r_V_10_fu_653_p2[57:29]}};
        icmp_ln833_2_reg_1331 <= icmp_ln833_2_fu_708_p2;
        icmp_ln833_reg_1325 <= icmp_ln833_fu_703_p2;
        isNeg_reg_1314 <= Ex_V_fu_671_p2[32'd7];
        ush_reg_1319 <= ush_fu_695_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        Med_V_reg_1253 <= {{r_V_9_fu_507_p2[99:20]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        Mx_zeros_V_reg_1296 <= Mx_zeros_V_fu_634_p1;
        p_Val2_24_reg_1285 <= p_Val2_24_fu_568_p3;
        p_Val2_7_reg_1291 <= p_Val2_7_fu_583_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        add_ln9_1_reg_1192 <= add_ln9_1_fu_403_p2;
        icmp_ln7_1_reg_1188 <= icmp_ln7_1_fu_397_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln9_reg_1157 <= add_ln9_fu_373_p2;
        icmp_ln7_reg_1153 <= icmp_ln7_fu_367_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_scaled_fixed2ieee_fu_341_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
        and_ln300_reg_1420 <= and_ln300_fu_1051_p2;
        ret_V_10_reg_1430 <= ret_V_10_fu_1096_p3;
        ret_V_11_reg_1435 <= ret_V_11_fu_1112_p3;
        select_ln311_reg_1425 <= select_ln311_fu_1065_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((out_r_full_n == 1'b0) & (phi_ln7_2_reg_327 == 1'd1)) & (1'b1 == ap_CS_fsm_state11) & (phi_ln7_2_reg_327 == 1'd1))) begin
        closepath_reg_1234 <= closepath_fu_450_p2;
        results_sign_V_1_reg_1215 <= tmp_8_reg_1176[32'd31];
        tmp_V_1_reg_1228 <= tmp_V_1_fu_447_p1;
        tmp_V_reg_1221 <= {{tmp_8_reg_1176[30:23]}};
        trunc_ln601_reg_1245 <= trunc_ln601_fu_485_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        icmp_ln833_1_reg_1268 <= icmp_ln833_1_fu_543_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        p_Val2_s_reg_1274 <= {{grp_fu_537_p2[76:19]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        result_V_reg_1410 <= {{r_V_14_fu_908_p2[57:29]}};
        ret_V_9_reg_1415 <= ret_V_9_fu_929_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        ret_V_reg_1405 <= ret_V_fu_890_p2;
        select_ln272_1_reg_1400 <= select_ln272_1_fu_869_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((in_r_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        tmp_8_reg_1176 <= in_r_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        trunc_ln1_reg_1390 <= {{r_V_12_fu_838_p2[44:23]}};
        trunc_ln662_1_reg_1395 <= {{r_V_13_fu_1141_p2[29:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state18) & (closepath_reg_1234 == 1'd0))) begin
        trunc_ln_i_i_reg_1280 <= {{grp_fu_537_p2[79:77]}};
    end
end

always @ (posedge ap_clk) begin
    if ((~((in_r_empty_n == 1'b0) & (icmp_ln7_reg_1153 == 1'd1)) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln7_reg_1153 == 1'd1))) begin
        x1_reg_1167 <= in_r_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        zext_ln7_1_reg_1197[6 : 0] <= zext_ln7_1_fu_409_p1[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((~((out_r_full_n == 1'b0) & (phi_ln7_2_reg_327 == 1'd1)) & (1'b1 == ap_CS_fsm_state11))) begin
        zext_ln7_2_reg_1210[3 : 0] <= zext_ln7_2_fu_427_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((~((in_r_empty_n == 1'b0) & (icmp_ln7_reg_1153 == 1'd1)) & (1'b1 == ap_CS_fsm_state3))) begin
        zext_ln7_reg_1162[6 : 0] <= zext_ln7_fu_379_p1[6 : 0];
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (trunc_ln8_2_fu_495_p1 == 1'd1))) begin
        debug_out = zext_ln7_2_reg_1210;
    end else if (((1'b1 == ap_CS_fsm_state8) & (trunc_ln8_1_fu_413_p1 == 1'd1))) begin
        debug_out = zext_ln7_1_reg_1197;
    end else if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln8_fu_383_p1 == 1'd1))) begin
        debug_out = zext_ln7_reg_1162;
    end else if (((1'b1 == ap_CS_fsm_state9) & (grp_xilly_decprint_fu_347_debug_out_ap_vld == 1'b1))) begin
        debug_out = grp_xilly_decprint_fu_347_debug_out;
    end else begin
        debug_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state12) & (trunc_ln8_2_fu_495_p1 == 1'd1)) | ((1'b1 == ap_CS_fsm_state8) & (trunc_ln8_1_fu_413_p1 == 1'd1)) | ((1'b1 == ap_CS_fsm_state4) & (trunc_ln8_fu_383_p1 == 1'd1)))) begin
        debug_out_ap_vld = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        debug_out_ap_vld = grp_xilly_decprint_fu_347_debug_out_ap_vld;
    end else begin
        debug_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln7_reg_1153 == 1'd1)))) begin
        in_r_blk_n = in_r_empty_n;
    end else begin
        in_r_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((in_r_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | (~((in_r_empty_n == 1'b0) & (icmp_ln7_reg_1153 == 1'd1)) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln7_reg_1153 == 1'd1)))) begin
        in_r_read = 1'b1;
    end else begin
        in_r_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state27) | ((1'b1 == ap_CS_fsm_state11) & (phi_ln7_2_reg_327 == 1'd1)))) begin
        out_r_blk_n = out_r_full_n;
    end else begin
        out_r_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((out_r_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state27))) begin
        out_r_din = p_Result_21_fu_1125_p4;
    end else if ((~((out_r_full_n == 1'b0) & (phi_ln7_2_reg_327 == 1'd1)) & (1'b1 == ap_CS_fsm_state11) & (phi_ln7_2_reg_327 == 1'd1))) begin
        out_r_din = y1_fu_489_p2;
    end else begin
        out_r_din = 'bx;
    end
end

always @ (*) begin
    if ((((out_r_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state27)) | (~((out_r_full_n == 1'b0) & (phi_ln7_2_reg_327 == 1'd1)) & (1'b1 == ap_CS_fsm_state11) & (phi_ln7_2_reg_327 == 1'd1)))) begin
        out_r_write = 1'b1;
    end else begin
        out_r_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_str3_ce0 = 1'b1;
    end else begin
        p_str3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        p_str4_ce0 = 1'b1;
    end else begin
        p_str4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        p_str5_ce0 = 1'b1;
    end else begin
        p_str5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((out_r_full_n == 1'b0) & (phi_ln7_2_reg_327 == 1'd1)) & (1'b1 == ap_CS_fsm_state11))) begin
        ref_4oPi_table_100_V_ce0 = 1'b1;
    end else begin
        ref_4oPi_table_100_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        second_order_float_2_ce0 = 1'b1;
    end else begin
        second_order_float_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        second_order_float_3_ce0 = 1'b1;
    end else begin
        second_order_float_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        second_order_float_s_ce0 = 1'b1;
    end else begin
        second_order_float_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if ((~((in_r_empty_n == 1'b0) & (icmp_ln7_reg_1153 == 1'd1)) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln7_reg_1153 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if ((~((in_r_empty_n == 1'b0) & (icmp_ln7_reg_1153 == 1'd1)) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln7_reg_1153 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln8_fu_383_p1 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((in_r_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln7_1_reg_1188 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (trunc_ln8_1_fu_413_p1 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((grp_xilly_decprint_fu_347_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if ((~((out_r_full_n == 1'b0) & (phi_ln7_2_reg_327 == 1'd1)) & (1'b1 == ap_CS_fsm_state11) & (phi_ln7_2_reg_327 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else if ((~((out_r_full_n == 1'b0) & (phi_ln7_2_reg_327 == 1'd1)) & (1'b1 == ap_CS_fsm_state11) & (phi_ln7_2_reg_327 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (trunc_ln8_2_fu_495_p1 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            if (((grp_scaled_fixed2ieee_fu_341_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state27 : begin
            if (((out_r_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state27))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B_V_fu_775_p1 = select_ln1310_fu_737_p3[21:0];

assign Ex_V_fu_671_p2 = (select_ln482_fu_643_p3 - zext_ln655_fu_668_p1);

assign Mx_bits_V_1_fu_578_p2 = (58'd0 - p_Val2_s_reg_1274);

assign Mx_zeros_V_fu_634_p1 = val_assign_fu_626_p3[4:0];

assign add_ln114_1_fu_456_p2 = ($signed(8'd194) + $signed(tmp_V_fu_438_p4));

assign add_ln114_fu_638_p2 = ($signed(8'd131) + $signed(tmp_V_reg_1221));

assign add_ln9_1_fu_403_p2 = (phi_ln7_1_reg_316 + 2'd1);

assign add_ln9_fu_373_p2 = (phi_ln7_reg_305 + 4'd1);

assign addr_V_fu_462_p3 = ((closepath_fu_450_p2[0:0] === 1'b1) ? 8'd63 : add_ln114_1_fu_456_p2);

assign and_ln300_1_fu_1073_p2 = (icmp_ln833_reg_1325 & icmp_ln833_1_reg_1268);

assign and_ln300_fu_1051_p2 = (icmp_ln833_reg_1325 & icmp_ln833_1_reg_1268);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state11 = ((out_r_full_n == 1'b0) & (phi_ln7_2_reg_327 == 1'd1));
end

always @ (*) begin
    ap_block_state3 = ((in_r_empty_n == 1'b0) & (icmp_ln7_reg_1153 == 1'd1));
end

assign closepath_fu_450_p2 = ((tmp_V_fu_438_p4 < 8'd126) ? 1'b1 : 1'b0);

assign grp_fu_537_p0 = grp_fu_537_p00;

assign grp_fu_537_p00 = Med_V_reg_1253;

assign grp_fu_537_p1 = grp_fu_537_p10;

assign grp_fu_537_p10 = p_Result_15_fu_523_p3;

assign grp_scaled_fixed2ieee_fu_341_ap_start = grp_scaled_fixed2ieee_fu_341_ap_start_reg;

assign grp_xilly_decprint_fu_347_ap_start = grp_xilly_decprint_fu_347_ap_start_reg;

assign icmp_ln7_1_fu_397_p2 = ((phi_ln7_1_reg_316 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln7_fu_367_p2 = ((phi_ln7_reg_305 == 4'd13) ? 1'b1 : 1'b0);

assign icmp_ln833_1_fu_543_p2 = ((tmp_V_1_reg_1228 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln833_2_fu_708_p2 = ((tmp_V_reg_1221 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln833_fu_703_p2 = ((tmp_V_reg_1221 == 8'd0) ? 1'b1 : 1'b0);

assign isNeg_fu_681_p3 = Ex_V_fu_671_p2[32'd7];

assign lhs_V_1_fu_875_p1 = $signed(t1_V_reg_1375);

assign lshr_ln1287_fu_722_p2 = Mx_V_reg_1302 >> sext_ln1311_1_fu_716_p1;

assign or_ln300_fu_1091_p2 = (icmp_ln833_2_reg_1331 | and_ln300_fu_1051_p2);

assign or_ln311_fu_1060_p2 = (select_ln271_fu_1044_p3 | icmp_ln833_2_reg_1331);

assign p_Repl2_3_fu_1120_p3 = ((and_ln300_reg_1420[0:0] === 1'b1) ? results_sign_V_1_reg_1215 : select_ln311_reg_1425);

assign p_Result_15_fu_523_p3 = {{1'd1}, {tmp_V_1_reg_1228}};

assign p_Result_16_fu_600_p3 = {{p_Result_i_i_i_fu_590_p4}, {1'd1}};

assign p_Result_17_fu_618_p3 = {{2'd3}, {p_Result_s_fu_608_p4}};

assign p_Result_18_fu_795_p3 = {{sin_basis_fu_789_p2}, {p_Result_i_i_fu_765_p4}};

assign p_Result_19_fu_940_p3 = p_Val2_20_fu_936_p1[32'd31];

assign p_Result_20_fu_962_p3 = {{results_sign_V_1_reg_1215}, {p_Val2_24_reg_1285}};

assign p_Result_21_fu_1125_p4 = {{{p_Repl2_3_fu_1120_p3}, {ret_V_10_reg_1430}}, {ret_V_11_reg_1435}};

assign p_Result_i_i_fu_765_p4 = {{select_ln1310_fu_737_p3[28:22]}};

assign p_Result_i_i_i_fu_590_p4 = {{p_Val2_7_fu_583_p3[57:29]}};

integer ap_tvar_int_0;

always @ (p_Result_16_fu_600_p3) begin
    for (ap_tvar_int_0 = 30 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 29 - 0) begin
            p_Result_s_fu_608_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_s_fu_608_p4[ap_tvar_int_0] = p_Result_16_fu_600_p3[29 - ap_tvar_int_0];
        end
    end
end

assign p_Val2_20_fu_936_p1 = grp_scaled_fixed2ieee_fu_341_ap_return;

assign p_Val2_24_fu_568_p3 = ((closepath_reg_1234[0:0] === 1'b1) ? 3'd0 : trunc_ln_i_i_reg_1280);

assign p_Val2_7_fu_583_p3 = ((trunc_ln745_fu_574_p1[0:0] === 1'b1) ? Mx_bits_V_1_fu_578_p2 : p_Val2_s_reg_1274);

assign p_str3_address0 = phi_ln7_cast_fu_362_p1;

assign p_str4_address0 = phi_ln7_1_cast_fu_392_p1;

assign p_str5_address0 = phi_ln7_2_cast_fu_422_p1;

assign phi_ln7_1_cast_fu_392_p1 = phi_ln7_1_reg_316;

assign phi_ln7_2_cast_fu_422_p1 = phi_ln7_2_reg_327;

assign phi_ln7_cast_fu_362_p1 = phi_ln7_reg_305;

assign r_V_10_fu_653_p2 = p_Val2_7_reg_1291 << zext_ln1253_fu_650_p1;

assign r_V_11_fu_1134_p0 = r_V_fu_810_p1;

assign r_V_11_fu_1134_p1 = r_V_fu_810_p1;

assign r_V_12_fu_838_p0 = second_order_float_6_reg_1380;

assign r_V_12_fu_838_p1 = r_V_12_fu_838_p10;

assign r_V_12_fu_838_p10 = B_V_reg_1345;

assign r_V_12_fu_838_p2 = ($signed(r_V_12_fu_838_p0) * $signed({{1'b0}, {r_V_12_fu_838_p1}}));

assign r_V_13_fu_1141_p0 = r_V_13_fu_1141_p00;

assign r_V_13_fu_1141_p00 = B_squared_V_reg_1370;

assign r_V_14_fu_908_p0 = ret_V_reg_1405;

assign r_V_14_fu_908_p1 = r_V_14_fu_908_p10;

assign r_V_14_fu_908_p10 = select_ln272_1_reg_1400;

assign r_V_14_fu_908_p2 = ($signed(r_V_14_fu_908_p0) * $signed({{1'b0}, {r_V_14_fu_908_p1}}));

assign r_V_9_fu_507_p2 = ref_4oPi_table_100_V_q0 << zext_ln744_fu_504_p1;

assign r_V_fu_810_p1 = B_trunc_V_reg_1350;

assign ref_4oPi_table_100_V_address0 = zext_ln498_fu_480_p1;

assign ret_V_10_fu_1096_p3 = ((or_ln300_fu_1091_p2[0:0] === 1'b1) ? select_ln300_1_fu_1083_p3 : tmp_V_2_fu_948_p4);

assign ret_V_11_fu_1112_p3 = ((or_ln300_fu_1091_p2[0:0] === 1'b1) ? select_ln300_3_fu_1104_p3 : tmp_V_3_fu_958_p1);

assign ret_V_13_fu_881_p2 = ($signed(lhs_V_1_fu_875_p1) + $signed(rhs_V_1_fu_878_p1));

assign ret_V_9_fu_929_p2 = ($signed(9'd0) - $signed(rhs_V_2_fu_925_p1));

assign ret_V_fu_890_p2 = ($signed(ret_V_13_fu_881_p2) + $signed(sext_ln657_fu_887_p1));

assign rhs_V_1_fu_878_p1 = $signed(trunc_ln1_reg_1390);

assign rhs_V_2_fu_925_p1 = $signed(select_ln272_fu_896_p3);

assign second_order_float_2_address0 = zext_ln498_1_fu_803_p1;

assign second_order_float_3_address0 = zext_ln498_1_fu_803_p1;

assign second_order_float_s_address0 = zext_ln498_1_fu_803_p1;

assign select_ln1310_fu_737_p3 = ((isNeg_reg_1314[0:0] === 1'b1) ? zext_ln1287_1_fu_727_p1 : shl_ln1253_fu_731_p2);

assign select_ln271_fu_1044_p3 = ((cos_basis_reg_1338[0:0] === 1'b1) ? tmp_fu_968_p18 : tmp_1_fu_1006_p18);

assign select_ln272_1_fu_869_p3 = ((cos_basis_reg_1338[0:0] === 1'b1) ? 29'd536870911 : Mx_V_reg_1302);

assign select_ln272_fu_896_p3 = ((cos_basis_reg_1338[0:0] === 1'b1) ? 8'd0 : Ex_V_reg_1309);

assign select_ln300_1_fu_1083_p3 = ((xor_ln300_fu_1077_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign select_ln300_3_fu_1104_p3 = ((xor_ln300_fu_1077_p2[0:0] === 1'b1) ? 23'd8388607 : 23'd0);

assign select_ln311_fu_1065_p3 = ((or_ln311_fu_1060_p2[0:0] === 1'b1) ? xor_ln311_fu_1055_p2 : p_Result_19_fu_940_p3);

assign select_ln482_fu_643_p3 = ((closepath_reg_1234[0:0] === 1'b1) ? add_ln114_fu_638_p2 : 8'd0);

assign sext_ln1311_1_fu_716_p1 = ush_reg_1319;

assign sext_ln1311_fu_713_p1 = ush_reg_1319;

assign sext_ln1334_fu_677_p1 = Ex_V_fu_671_p2;

assign sext_ln657_fu_887_p1 = $signed(trunc_ln662_1_reg_1395);

assign shl_ln1253_fu_731_p2 = zext_ln1287_fu_719_p1 << sext_ln1311_fu_713_p1;

assign sin_basis_fu_789_p2 = (cos_basis_fu_744_p10 ^ 1'd1);

assign sub_ln1311_fu_689_p2 = ($signed(9'd0) - $signed(sext_ln1334_fu_677_p1));

assign tmp_3_fu_470_p4 = {{addr_V_fu_462_p3[7:4]}};

assign tmp_V_1_fu_447_p1 = tmp_8_reg_1176[22:0];

assign tmp_V_2_fu_948_p4 = {{p_Val2_20_fu_936_p1[30:23]}};

assign tmp_V_3_fu_958_p1 = p_Val2_20_fu_936_p1[22:0];

assign tmp_V_fu_438_p4 = {{tmp_8_reg_1176[30:23]}};

assign trunc_ln601_fu_485_p1 = addr_V_fu_462_p3[3:0];

assign trunc_ln745_fu_574_p1 = p_Val2_24_fu_568_p3[0:0];

assign trunc_ln8_1_fu_413_p1 = debug_ready[0:0];

assign trunc_ln8_2_fu_495_p1 = debug_ready[0:0];

assign trunc_ln8_fu_383_p1 = debug_ready[0:0];

assign ush_fu_695_p3 = ((isNeg_fu_681_p3[0:0] === 1'b1) ? sub_ln1311_fu_689_p2 : sext_ln1334_fu_677_p1);


always @ (p_Result_17_fu_618_p3) begin
    if (p_Result_17_fu_618_p3[0] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd0;
    end else if (p_Result_17_fu_618_p3[1] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd1;
    end else if (p_Result_17_fu_618_p3[2] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd2;
    end else if (p_Result_17_fu_618_p3[3] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd3;
    end else if (p_Result_17_fu_618_p3[4] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd4;
    end else if (p_Result_17_fu_618_p3[5] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd5;
    end else if (p_Result_17_fu_618_p3[6] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd6;
    end else if (p_Result_17_fu_618_p3[7] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd7;
    end else if (p_Result_17_fu_618_p3[8] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd8;
    end else if (p_Result_17_fu_618_p3[9] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd9;
    end else if (p_Result_17_fu_618_p3[10] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd10;
    end else if (p_Result_17_fu_618_p3[11] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd11;
    end else if (p_Result_17_fu_618_p3[12] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd12;
    end else if (p_Result_17_fu_618_p3[13] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd13;
    end else if (p_Result_17_fu_618_p3[14] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd14;
    end else if (p_Result_17_fu_618_p3[15] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd15;
    end else if (p_Result_17_fu_618_p3[16] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd16;
    end else if (p_Result_17_fu_618_p3[17] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd17;
    end else if (p_Result_17_fu_618_p3[18] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd18;
    end else if (p_Result_17_fu_618_p3[19] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd19;
    end else if (p_Result_17_fu_618_p3[20] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd20;
    end else if (p_Result_17_fu_618_p3[21] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd21;
    end else if (p_Result_17_fu_618_p3[22] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd22;
    end else if (p_Result_17_fu_618_p3[23] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd23;
    end else if (p_Result_17_fu_618_p3[24] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd24;
    end else if (p_Result_17_fu_618_p3[25] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd25;
    end else if (p_Result_17_fu_618_p3[26] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd26;
    end else if (p_Result_17_fu_618_p3[27] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd27;
    end else if (p_Result_17_fu_618_p3[28] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd28;
    end else if (p_Result_17_fu_618_p3[29] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd29;
    end else if (p_Result_17_fu_618_p3[30] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd30;
    end else if (p_Result_17_fu_618_p3[31] == 1'b1) begin
        val_assign_fu_626_p3 = 32'd31;
    end else begin
        val_assign_fu_626_p3 = 32'd32;
    end
end

assign xor_ln300_fu_1077_p2 = (1'd1 ^ and_ln300_1_fu_1073_p2);

assign xor_ln311_fu_1055_p2 = (icmp_ln833_2_reg_1331 ^ 1'd1);

assign y1_fu_489_p2 = (32'd1 + x1_reg_1167);

assign zext_ln1253_fu_650_p1 = Mx_zeros_V_reg_1296;

assign zext_ln1287_1_fu_727_p1 = lshr_ln1287_fu_722_p2;

assign zext_ln1287_fu_719_p1 = Mx_V_reg_1302;

assign zext_ln498_1_fu_803_p1 = p_Result_18_fu_795_p3;

assign zext_ln498_fu_480_p1 = tmp_3_fu_470_p4;

assign zext_ln655_fu_668_p1 = Mx_zeros_V_reg_1296;

assign zext_ln744_fu_504_p1 = trunc_ln601_reg_1245;

assign zext_ln7_1_fu_409_p1 = p_str4_q0;

assign zext_ln7_2_fu_427_p1 = p_str5_q0;

assign zext_ln7_fu_379_p1 = p_str3_q0;

always @ (posedge ap_clk) begin
    zext_ln7_reg_1162[7] <= 1'b0;
    zext_ln7_1_reg_1197[7] <= 1'b0;
    zext_ln7_2_reg_1210[7:4] <= 4'b0000;
end

endmodule //xillybus_wrapper
